### ISSUE TITLE
Rewrite TheHive4py library

### ISSUE THREAD

**Issue by nadouani** [TheHive-Project/TheHive4py#85]
### Request Type
Feature Request

### Problem Description
TheHive4py < 2.0 was initially a quick attempt to provide a python library on top of TheHive REST apis. The current version has a lot of limitations and lacks of consistency. 

The goal of this issue is to rewrite it completely, introducing the minimal breaking changes and making sure to be backward compatible for almost all the existing methods.

We will use the same architecture as Cortex4py rewritten version.

### Features to include
- [x] https://github.com/TheHive-Project/TheHive4py/issues/6 Update task
- [x] https://github.com/TheHive-Project/TheHive4py/issues/7 Update observable
- [ ] https://github.com/TheHive-Project/TheHive4py/issues/9 Add an option to get case tasks from get_case method
- [x] https://github.com/TheHive-Project/TheHive4py/issues/12 Make api return dictionaries, not raw responses
- [x] https://github.com/TheHive-Project/TheHive4py/issues/89 Function to merge cases
- [x] https://github.com/TheHive-Project/TheHive4py/issues/62 Add the ability to search for all active observables where ioc:true without knowing caseIds
- [ ] https://github.com/TheHive-Project/TheHive4py/issues/126 Add ioc and sighted attributes to case and alert artifacts
- [ ] https://github.com/TheHive-Project/TheHive4py/issues/127 Models Case and CaseTemplate don't have PAP attribute
- [ ] Include fixes and features from 1.x branch

**Comment by mgabriel-silva** [comment]
Please include #117 if possible.
It would be of great help to teams who use alerts.

**Comment by IAreKyleW00t** [comment]
@nadouani Just curious on the status of `2.0.0` - I was in the process of writing a "better" API but it looks like you're already ahead of me! I'd much rather contribute to this than have an unofficial competing project out there.

**Comment by nicolaipre** [comment]
I am currently using a simple wrapper I made around the current API, and it works fine, but I was wondering if there are any updates on this?

**Comment by alisp7** [comment]
hi 
this is my first time to use TheHive with TheHive4py 1.7.2 i wanted to Set up TheHive API to establish API connectivity to TheHive i completely confused  where should i go and what should i do i couldn't find the configuration path of the TheHive4py. Would you please me what should i do and where is the configuration file of TheHive4py is located?
